manifest = "945bfa07f1cd8d43f6166968a91abdc5f875133c2e24a25990b09427e1e8360c"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-functional"
target = "//:functional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
target = "//:lexical_cast"

[[dependency]]
package = "github.com/buckaroo-pm/boost-rational"
target = "//:rational"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.58.0" ]
revision = "ce293ccd59612db24c7ce3d98d6cd624952199af"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.58.0" ]
revision = "2d03b5bf34bf73cb2e4e2a7665c12cebb2d70890"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.58.0" ]
revision = "ac721f66265e383ac6d7b96996e902332d12783d"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.58.0" ]
revision = "91b063a3dc7abe79307276475ce8214d33408160"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.58.0" ]
revision = "f13bdc028f96f77a47386c5d4290205f5bd31d32"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.58.0" ]
revision = "ba2389bfd836700138f7fbd65858501d75276a05"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "1.58.0" ]
revision = "3310459a198e7b6daa3115e9c0799f6f1832fe56"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.58.0" ]
revision = "99a85accd5607ac5a79f95fce3dbcdd95e0b5f45"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.58.0" ]
revision = "56d073a8276bae5f86b88b8e967da2e125280c0b"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.58.0" ]
revision = "a36f15fe51460b013e423ed1c83a0fcb719752ba"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.58.0" ]
revision = "2782837f081e7128e2c90d0318deeb6a1a56b782"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.58.0" ]
revision = "d218408d73f3ab5056f170a11e7adffc46ff8f66"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.58.0" ]
revision = "b82e8654df7bb46ef4121cc340cd065a95b7580d"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "1.58.0" ]
revision = "0fb5f7a58955b190491c37f6011876f887b798b7"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.58.0" ]
revision = "6b05293620f9f352f8f37a482683dd888e5fbcd8"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "1.58.0" ]
revision = "9e9eebff4c17d29d2b941dda33872bbf44e2d9ca"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.58.0" ]
revision = "38bbc6135995cb588347bf550798e80e73c09977"

[lock."github.com/buckaroo-pm/boost-lexical_cast"]
versions = [ "1.58.0" ]
revision = "93635ccae20d17e29c14fa56e9cb5ed6984b22ce"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.58.0" ]
revision = "64a4ee9e7b86170ee420f688da3eb62185864c10"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.58.0" ]
revision = "4d4b55414dbb748251175df77ac6c3032cc79121"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "1.58.0" ]
revision = "f9f7db4f10577895e7cad767e6f6d7ebd87270c0"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.58.0" ]
revision = "aa995a705134238256af161bf9627a095fc99cdc"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.58.0" ]
revision = "7dcb0855fb3a3e5e13cdd5c7b7464a27ec27091d"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.58.0" ]
revision = "2b5f853e75e5811875cc344e5a6824cec279e9a7"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.58.0" ]
revision = "b875a58b71ad042b4fd1f1a4cf9ae338d776ff58"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "1.58.0" ]
revision = "2a1b51755a5c6faab5a57713737c23a21b211f83"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.58.0" ]
revision = "e11d8e4fdad6cbaf2f67f6ef04a2b2f5b9e800db"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.58.0" ]
revision = "f777b1eef66c8145f13ab1077dc6585fbbb7f26a"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.58.0" ]
revision = "4d5c3a9eab5c2ab8391ad4c4308548c61d349727"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.58.0" ]
revision = "43296e787bc84ab252eaa787ad2b2a559e02bca3"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.58.0" ]
revision = "7486c1bdd14951698025082023c90379990ed7fb"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.58.0" ]
revision = "707eee805b5b0c9f914b0cfb154d90609b119979"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.58.0" ]
revision = "464be14cff1e4aa654507df1a6313d366a45d974"
