manifest = "4529b4c453e6f5c3f8a1050b1e4f0ec80369bd78e5b5349ecfcf942522d46308"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-functional"
target = "//:functional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
target = "//:lexical_cast"

[[dependency]]
package = "github.com/buckaroo-pm/boost-rational"
target = "//:rational"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.62.0" ]
revision = "a0ef4b8d1aee3a56fc25900b562c46ff6fb5a3ef"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.62.0" ]
revision = "95e6537d5ade0e59fdf9d9deb693e1209cbe63ba"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.62.0" ]
revision = "484f0f9359c0896a0ea9ae1f471c4586b2bb1591"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.62.0" ]
revision = "8b7c48e29eba8eaf4f1f8d1641099762c6e5bdda"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.62.0" ]
revision = "03014315e0e51177dc32b09f4f8b0bf501b9fae7"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.62.0" ]
revision = "8e0bd7d950d98d4dd62a61b31ad6cd90e0ab3fd9"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "1.62.0" ]
revision = "d48d3cda3c131ad54fd33b6a789536f8fd043252"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.62.0" ]
revision = "e69637e8ed521c46dfe802587b6b769921afbe15"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.62.0" ]
revision = "aabf1b51ad20471ec869ae8db30d4f8da170e6a2"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.62.0" ]
revision = "61e5cbe0edab2492008d5e8a7966ac70aada9dfa"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.62.0" ]
revision = "1b516c700dd073c8a500fdfd016dc35c1713fdb8"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.62.0" ]
revision = "e5b2eb705e4dadf103cdd69eed1355a9cf45abd9"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.62.0" ]
revision = "e11fe4e1ac2a4434a7867514778b6251a676b83d"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "1.62.0" ]
revision = "aa2ca4c90d367496ac82435f797d636348c7dee3"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.62.0" ]
revision = "9378469b54345a1ac6c6ae67a50cff8e56c3e993"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "1.62.0" ]
revision = "40a85b4edee6aac944aabef5ac462086eb48d72d"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.62.0" ]
revision = "24ce8373364d9359da9a6f65ecdb59a376bccf7f"

[lock."github.com/buckaroo-pm/boost-lexical_cast"]
versions = [ "1.62.0" ]
revision = "27b1a635ec9a4c3b4dba673d12c6bb2aff0ba908"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.62.0" ]
revision = "edb8a3c19e43ae295c9a3f059f98f5c6382bd436"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.62.0" ]
revision = "e8848a7e20619b49745e5223b8de200eeaa5f66f"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "1.62.0" ]
revision = "cc31c2acff4334b9399022f4d0f920d68777aea1"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.62.0" ]
revision = "6c9007ad4309ebf7a6613214709d1507349e4cef"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.62.0" ]
revision = "e0bffc2812a69bfeffaa3d56128c505048890c01"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.62.0" ]
revision = "aed0a64c4a565f629c3ae67e1ab0657ff6934db7"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.62.0" ]
revision = "cf65b2fae4032684d972192fce51b4f388b3bd27"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "1.62.0" ]
revision = "d9d35424afea4f20fa313fd7a3016e8d23ba14ae"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.62.0" ]
revision = "8d66a9c97d7056a782989b37e933d07b46113755"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.62.0" ]
revision = "92612185e7bae70d2e2a614509f031c535331c14"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.62.0" ]
revision = "4dc277e659990e4fb86a55c450c8249ec3bd3b50"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.62.0" ]
revision = "c1b11694cb0d4da9604af2d663719110f153dba0"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.62.0" ]
revision = "2e64310825036f60972e8f91189aa4b36647a47d"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.62.0" ]
revision = "7e89565d922a06a6ec9e7dc10be84e17a491414c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.62.0" ]
revision = "3ddcf9ceb2f5b7894128928e2bc8bb03ddca16b7"
