targets = [ "//:multiprecision" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-functional"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-rational"
version = "1.65.1"
